"""Inherits `account.move.send.wizard` to substitute the standard PDF report
with the latest pdfgen-generated PDF (or a freshly-generated one).

The wizard's stock view shows a `mail_attachments_widget` JSON list. The
"placeholder" entry — the standard report that pdfgen Odoo will render at
send time — is what we substitute. When `pdfgen_use_custom` is on:

  - if a recent pdfgen attachment already exists on the move, we drop the
    placeholder and add the existing attachment as a regular entry;
  - else we generate the PDF synchronously via the mixin, then add the
    fresh attachment to the widget.

Generation failure is surfaced via `pdfgen_error` (read-only Char shown in
the modal) and the toggle force-resets to OFF so the user can fall back to
the standard report. A missing template is not a failure — the placeholder
stays until the user picks one.
"""

import logging

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class AccountMoveSendWizard(models.TransientModel):
    _name = "account.move.send.wizard"
    _inherit = ["account.move.send.wizard", "pdfgen.send.mixin"]

    pdfgen_configured = fields.Boolean(
        string="PDF API configured", compute="_compute_pdfgen_configured"
    )
    pdfgen_use_custom = fields.Boolean(
        string="Use PDF API document",
        compute="_compute_pdfgen_use_custom",
        # Stored so a user's flip sticks: a non-stored compute is re-evaluated
        # on every round-trip, which would snap the toggle back ON.
        store=True,
        readonly=False,
        help=(
            "Replace the standard invoice report with the latest document "
            "generated by pdfgeneratorapi.com (or generate one synchronously "
            "from the dataset's default template)."
        ),
    )
    pdfgen_template_id = fields.Selection(
        selection="_selection_pdfgen_template_id",
        string="PDF API Template",
        compute="_compute_pdfgen_template_id",
        store=True,
        readonly=False,
    )
    pdfgen_preview_html = fields.Html(
        string="Preview",
        sanitize=False,
        readonly=True,
        compute="_compute_pdfgen_preview_html",
    )
    # Labelled even though the view renders it without one: the derived
    # label ("Pdfgen Error") would leak the internal name into tooltips and
    # translation exports.
    pdfgen_error = fields.Char(string="PDF API notice", readonly=True)

    @api.depends("move_id")
    def _compute_pdfgen_configured(self):
        for wiz in self:
            wiz.pdfgen_configured = bool(wiz.move_id) and bool(wiz._pdfgen_dataset(wiz.move_id))

    @api.depends("move_id")
    def _compute_pdfgen_use_custom(self):
        for wiz in self:
            wiz.pdfgen_use_custom = wiz._pdfgen_should_default_on(wiz.move_id)

    @api.depends("move_id", "pdfgen_use_custom")
    def _compute_pdfgen_template_id(self):
        for wiz in self:
            if wiz.pdfgen_use_custom:
                wiz.pdfgen_template_id = wiz._pdfgen_pick_template_id(wiz.move_id)
            else:
                wiz.pdfgen_template_id = False

    @api.depends("pdfgen_template_id", "pdfgen_use_custom")
    def _compute_pdfgen_preview_html(self):
        for wiz in self:
            if wiz.pdfgen_use_custom and wiz.pdfgen_template_id:
                wiz.pdfgen_preview_html = wiz._pdfgen_render_preview_html(
                    wiz.pdfgen_template_id, wiz.move_id
                )
            else:
                wiz.pdfgen_preview_html = False

    @api.model
    def _selection_pdfgen_template_id(self):
        # Same live-fetch the dataset's default template uses — share via the
        # dataset selection helper so we hit the API at most once per request.
        return self.env["pdfgen.model.dataset"]._selection_default_template_id()

    @api.depends(
        "template_id",
        "invoice_edi_format",
        "extra_edis",
        "pdf_report_id",
        "pdfgen_use_custom",
        "pdfgen_template_id",
    )
    # pylint-odoo's missing-return rule fires because we use super(); for
    # compute methods Odoo expects no return value, so suppress.
    # pylint: disable=missing-return
    def _compute_mail_attachments_widget(self):
        # Defer to the upstream compute first so manual / dynamic / extra
        # entries are present, then post-process to swap the placeholder.
        super()._compute_mail_attachments_widget()
        for wiz in self:
            if not wiz.pdfgen_use_custom:
                continue
            wiz.pdfgen_error = False
            try:
                widget = wiz._pdfgen_apply_substitution(wiz.mail_attachments_widget or [])
            except UserError as e:
                wiz.pdfgen_error = str(e)
                wiz.pdfgen_use_custom = False
                continue
            wiz.mail_attachments_widget = widget

    def _pdfgen_apply_substitution(self, widget):
        """Make the pdfgen PDF the move's official report and reflect that
        in the wizard's attachment widget.

        Steps, in order so each one has a consistent view of state:

          1. Find / mint the pdfgen attachment for the chosen template.
          2. Point `move.invoice_pdf_report_id` at it — Odoo's `Document
             Preview` pane and `_get_invoice_extra_attachments` both read
             this field.
          3. Strip the placeholder entry (the to-be-generated standard
             report) and any pre-existing extra-attachment entries that
             aren't manual user uploads. Keep template / manual / dynamic
             entries untouched.
          4. Append the pdfgen attachment as the sole protected PDF.
        """
        self.ensure_one()
        if not self.pdfgen_template_id:
            # Not an error: the toggle defaults ON wherever the connector is
            # set up, and the view marks the template field required. Ask for
            # a template and leave the standard report placeholder in place.
            self.pdfgen_error = _("Pick a template to attach a PDF API document.")
            return widget
        # Pin the move recordset locally — `ir.attachment.create` below
        # invalidates wizard caches, and re-reading `self.move_id` on a
        # NewId wizard would re-trigger default_get (and crash without
        # active_ids in context).
        move = self.move_id
        latest = self._pdfgen_latest_pdfgen_attachment(move)
        if not latest or (
            self.pdfgen_template_id
            and latest.description
            and not latest.description.endswith(f":{self.pdfgen_template_id}")
        ):
            latest = self._pdfgen_generate_attachment(self.pdfgen_template_id, move)
        # 2. Transfer the `invoice_pdf_report_file` res_field claim from
        # the standard report to our pdfgen attachment so Odoo's
        # computed `invoice_pdf_report_id` resolves to ours and the
        # form-view preview pane reflects it.
        self._pdfgen_promote_attachment(move, latest)
        # 3. Strip placeholder + non-manual existing-PDF entries.
        out = []
        for w in widget:
            is_placeholder = w.get("placeholder") and not w.get("dynamic_report")
            is_existing_pdf = (
                not w.get("placeholder")
                and not w.get("manual")
                and w.get("mimetype") == "application/pdf"
                and w.get("protect_from_deletion")
            )
            if is_placeholder or is_existing_pdf:
                continue
            out.append(w)
        # 4. Inject the pdfgen attachment.
        out.append(
            {
                "id": latest.id,
                "name": latest.name,
                "mimetype": "application/pdf",
                "placeholder": False,
                "protect_from_deletion": True,
            }
        )
        return out
