"""Inherits `mail.compose.message` so the generic Send flow can ship the
PDF API document instead of the standard QWeb report.

`account.move` has a dedicated Send wizard (`account.move.send.wizard`,
handled in the Invoicing bridge). Every other document — quotations,
purchase orders, delivery slips, … — goes through the mail composer, so
one override here covers all of them at once: the panel only shows up
when the composer's model has an active `pdfgen.model.dataset`.

Substitution rules:

  - The entries we replace are the report attachments the composer just
    rendered from the template's `report_template_ids`. Those live on
    `mail.compose.message` with `res_id = 0`; files the user uploads by
    hand go to the *document's* thread and template-static attachments
    stay on `mail.template`, so neither is ever touched.
  - Flipping the toggle back off re-renders the template's report, so
    switching back and forth always lands on a sendable attachment. Files
    the user attached by hand survive either way.
  - Generation failure surfaces in `pdfgen_error` and forces the toggle
    off so the user can still send the standard report. A missing template
    is not a failure — the standard report simply stays put until one is
    picked.
"""

import logging

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class MailComposeMessage(models.TransientModel):
    _name = "mail.compose.message"
    _inherit = ["mail.compose.message", "pdfgen.send.mixin"]

    pdfgen_configured = fields.Boolean(
        string="PDF API configured", compute="_compute_pdfgen_configured"
    )
    pdfgen_use_custom = fields.Boolean(
        string="Use PDF API document",
        compute="_compute_pdfgen_use_custom",
        # Stored so a user's flip sticks: a non-stored compute is re-evaluated
        # on every round-trip, which would snap the toggle back ON.
        store=True,
        readonly=False,
        help=(
            "Replace the standard report attachment with the latest document "
            "generated by pdfgeneratorapi.com (or generate one from the "
            "template picked below)."
        ),
    )
    pdfgen_template_id = fields.Selection(
        selection="_selection_pdfgen_template_id",
        string="PDF API Template",
        compute="_compute_pdfgen_template_id",
        store=True,
        readonly=False,
    )
    pdfgen_preview_html = fields.Html(
        string="Preview",
        sanitize=False,
        readonly=True,
        compute="_compute_pdfgen_preview_html",
    )
    # Labelled even though the view renders it without one: the derived
    # label ("Pdfgen Error") would leak the internal name into tooltips and
    # translation exports.
    pdfgen_error = fields.Char(string="PDF API notice", readonly=True)

    # Field changes that can invalidate the current attachment set.
    _PDFGEN_SYNC_TRIGGERS = frozenset(
        {"pdfgen_use_custom", "pdfgen_template_id", "template_id", "attachment_ids"}
    )

    # ------------------------------------------------------------- targeting

    def _pdfgen_target_record(self) -> models.Model:
        """The single record the composer is about to mail, or an empty
        recordset when pdfgen substitution doesn't apply (mass mail, batch,
        log note, unknown model).
        """
        self.ensure_one()
        if self.composition_mode != "comment" or self.composition_batch:
            return self.env["mail.compose.message"].browse()
        if not self.model or self.model not in self.env:
            return self.env["mail.compose.message"].browse()
        try:
            res_ids = self._evaluate_res_ids()
        except (ValueError, TypeError):  # pragma: no cover - malformed res_ids
            return self.env["mail.compose.message"].browse()
        if not res_ids or len(res_ids) != 1:
            return self.env["mail.compose.message"].browse()
        record = self.env[self.model].browse(res_ids).exists()
        return record

    # -------------------------------------------------------------- computes

    @api.depends("model", "res_ids", "res_domain", "composition_mode", "composition_batch")
    def _compute_pdfgen_configured(self) -> None:
        for composer in self:
            record = composer._pdfgen_target_record()
            composer.pdfgen_configured = bool(record) and bool(composer._pdfgen_dataset(record))

    @api.depends("model", "res_ids", "res_domain", "composition_mode", "template_id")
    def _compute_pdfgen_use_custom(self) -> None:
        """ON by default wherever the connector is set up for the model and
        the composer is about to attach a standard report.

        The `report_template_ids` condition is what keeps the chatter's plain
        "Send message" composer (no template, no report) out of it — a note
        emailed from the chatter should never grow an unexpected PDF. The
        toggle is still there if the user wants one.
        """
        for composer in self:
            record = composer._pdfgen_target_record()
            composer.pdfgen_use_custom = (
                bool(record)
                and bool(composer.template_id.report_template_ids)
                and composer._pdfgen_should_default_on(record)
            )

    @api.depends("model", "res_ids", "pdfgen_use_custom")
    def _compute_pdfgen_template_id(self) -> None:
        for composer in self:
            record = composer._pdfgen_target_record()
            if composer.pdfgen_use_custom and record:
                composer.pdfgen_template_id = composer._pdfgen_pick_template_id(record)
            else:
                composer.pdfgen_template_id = False

    @api.depends("pdfgen_template_id", "pdfgen_use_custom")
    def _compute_pdfgen_preview_html(self) -> None:
        for composer in self:
            record = composer._pdfgen_target_record()
            if composer.pdfgen_use_custom and composer.pdfgen_template_id and record:
                composer.pdfgen_preview_html = composer._pdfgen_render_preview_html(
                    composer.pdfgen_template_id, record
                )
            else:
                composer.pdfgen_preview_html = False

    @api.model
    def _selection_pdfgen_template_id(self) -> list[tuple[str, str]]:
        # Shared with the dataset's default-template field so a request hits
        # the templates endpoint at most once.
        return self.env["pdfgen.model.dataset"]._selection_default_template_id()

    # pylint-odoo's missing-return rule fires because we call super(); compute
    # methods must not return a value, so suppress it.
    # pylint: disable=missing-return
    def _compute_attachment_ids(self) -> None:
        """Run the stock template/report computation, then swap the report for
        the PDF API document when the toggle starts ON.

        This covers opening the dialog. Later edits never reach a compute —
        the composer form goes straight from a field change to `web_save`
        with `attachment_ids` already in the payload — so those are handled
        in `create` / `write` below.
        """
        super()._compute_attachment_ids()
        for composer in self:
            if composer.pdfgen_use_custom:
                composer._pdfgen_substitute_or_fallback()

    # ------------------------------------------------------- persistence hooks

    @api.model_create_multi
    def create(self, vals_list: list[dict]) -> models.Model:
        composers = super().create(vals_list)
        composers._pdfgen_sync_attachments()
        return composers

    def write(self, vals: dict) -> bool:
        res = super().write(vals)
        if self._PDFGEN_SYNC_TRIGGERS & vals.keys():
            self._pdfgen_sync_attachments()
        return res

    def _pdfgen_sync_attachments(self) -> None:
        """Bring `attachment_ids` in line with the toggle after a save.

        The dialog saves the record with whatever attachments the client was
        showing, so this is where a user's flip of the toggle (or a different
        template) actually takes effect. Idempotent, and re-entrant writes are
        cut off by the context flag.
        """
        if self.env.context.get("pdfgen_syncing"):
            return
        for composer in self.with_context(pdfgen_syncing=True):
            if not composer.pdfgen_configured:
                continue
            if composer.pdfgen_use_custom:
                composer._pdfgen_substitute_or_fallback()
            else:
                composer._pdfgen_drop_generated()

    # ------------------------------------------------------------ mechanics

    def _pdfgen_substitute_or_fallback(self) -> None:
        """Apply the substitution, degrading to the standard report (toggle
        forced OFF, message in `pdfgen_error`) when generation fails.
        """
        self.ensure_one()
        self.pdfgen_error = False
        try:
            self._pdfgen_substitute()
        except UserError as e:
            # The stock compute already left the standard report in place;
            # just back off and say why.
            self.pdfgen_error = str(e)
            self.pdfgen_use_custom = False

    def _pdfgen_substitute(self) -> None:
        """Replace the rendered standard report with the PDF API document.

        Raises `UserError` (surfaced in the dialog by the caller) when
        generation fails.
        """
        self.ensure_one()
        record = self._pdfgen_target_record()
        if not record:
            return
        template_id = self.pdfgen_template_id or self._pdfgen_pick_template_id(record)
        if not template_id:
            # Not an error: the toggle defaults ON, and the view already marks
            # the template field required. Prompt for one and leave the
            # standard report attached until it arrives.
            self.pdfgen_error = _("Pick a template to attach a PDF API document.")
            return
        attachment = self._pdfgen_latest_pdfgen_attachment(record)
        if not attachment or (
            attachment.description and not attachment.description.endswith(f":{template_id}")
        ):
            attachment = self._pdfgen_generate_attachment(template_id, record)
        # No-op unless the model exposes a canonical PDF binary field
        # (account.move); keeps the form preview pane in sync where it exists.
        self._pdfgen_promote_attachment(record, attachment)

        # Out: the rendered standard report(s) plus anything a previous pass
        # injected (template switch) — everything else the user put there stays.
        dropped = self.attachment_ids.filtered(
            lambda a: self._pdfgen_is_rendered_report(a) or self._pdfgen_is_marked(a)
        )
        # `update` rather than a direct assignment: the field belongs to the
        # inherited model, and pylint flags writing it as an ad-hoc attribute.
        self.update({"attachment_ids": (self.attachment_ids - dropped) | attachment})

    def _pdfgen_drop_generated(self) -> None:
        """Toggle off: take our document out and put the standard report back.

        The report is re-rendered rather than restored from a stash — nothing
        the wizard remembers survives the composer's save/reload cycle.
        """
        self.ensure_one()
        ours = self.attachment_ids.filtered(self._pdfgen_is_marked)
        if not ours:
            return
        keep = self.attachment_ids - ours
        if not keep.filtered(self._pdfgen_is_rendered_report):
            # Our document had replaced the report; render it again and merge
            # the user's own files back in.
            user_files = keep
            # Calling the parent compute by hand is the point here — it is the
            # only code that knows how to render the template's reports.
            # pylint: disable=super-method-mismatch
            super()._compute_attachment_ids()
            keep = self.attachment_ids | user_files
        self.update({"attachment_ids": keep})

    def _pdfgen_is_user_attachment(self, attachment: models.Model) -> bool:
        """True for files that are the user's, not ours or Odoo's: they must
        survive both the stock compute's reset and the substitution.
        """
        return not self._pdfgen_is_rendered_report(attachment) and not self._pdfgen_is_marked(
            attachment
        )

    @staticmethod
    def _pdfgen_is_marked(attachment: models.Model) -> bool:
        """True for attachments this addon generated (any template)."""
        return bool(attachment.description) and attachment.description.startswith("pdfgen:")

    @staticmethod
    def _pdfgen_is_rendered_report(attachment: models.Model) -> bool:
        """True for the PDFs the composer just rendered off the template's
        reports.

        `_compute_attachment_ids` creates those with `res_model =
        'mail.compose.message'` and `res_id = 0`. Manual uploads are stored
        against the document's own thread and template-static files against
        `mail.template`, so this never swallows a user's file.

        Mimetype is deliberately not part of the test: a report renders as
        HTML whenever the PDF renderer is unavailable (and in tests), and
        that stand-in is exactly what we're replacing.
        """
        return attachment.res_model == "mail.compose.message" and not attachment.res_id
