{
    "name": "PDF Generator API Connector",
    "version": "19.0.6.0.0",
    "category": "Productivity/Documents",
    "summary": "Framework: generate custom PDFs of any record via pdfgeneratorapi.com",
    "author": "PDF Generator API",
    "website": "https://pdfgeneratorapi.com",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_config_parameter.xml",
        "views/res_config_settings_views.xml",
        "views/pdfgen_coverage_wizard_views.xml",
        "views/pdfgen_template_editor_wizard_views.xml",
        "views/pdfgen_model_dataset_views.xml",
        "views/generate_pdf_wizard_views.xml",
        "views/pdfgen_async_dispatch_wizard_views.xml",
        "views/pdfgen_async_job_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pdfgeneratorapi_connector/static/src/mapping_editor/field_palette.js",
            "pdfgeneratorapi_connector/static/src/mapping_editor/field_palette.xml",
            "pdfgeneratorapi_connector/static/src/mapping_editor/droppable_field_selector.js",
            "pdfgeneratorapi_connector/static/src/mapping_editor/mapping_editor.scss",
            "pdfgeneratorapi_connector/static/src/template_editor/editor_iframe_field.js",
            "pdfgeneratorapi_connector/static/src/template_editor/editor_iframe_field.xml",
            "pdfgeneratorapi_connector/static/src/template_editor/template_editor.scss",
            "pdfgeneratorapi_connector/static/src/settings/settings.scss",
        ],
        "web.assets_unit_tests": [
            "pdfgeneratorapi_connector/static/tests/**/*.test.js",
        ],
    },
    "images": ["static/description/icon.png"],
    "application": True,
}
