{
    "name": "PDF Generator API",
    "version": "18.0.7.3.2",
    "category": "Productivity/Documents",
    "summary": "Drag-and-drop PDF templates for Odoo, no QWeb or XML",
    "author": "PDF Generator API",
    "website": "https://pdfgeneratorapi.com",
    "support": "support@pdfgeneratorapi.com",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_config_parameter.xml",
        "views/res_config_settings_views.xml",
        "views/pdfgen_coverage_wizard_views.xml",
        "views/pdfgen_template_editor_wizard_views.xml",
        "views/pdfgen_model_dataset_views.xml",
        "views/generate_pdf_wizard_views.xml",
        "views/mail_compose_message_views.xml",
        "views/pdfgen_async_dispatch_wizard_views.xml",
        "views/pdfgen_async_job_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pdfgeneratorapi_connector/static/src/mapping_editor/field_palette.js",
            "pdfgeneratorapi_connector/static/src/mapping_editor/field_palette.xml",
            "pdfgeneratorapi_connector/static/src/mapping_editor/droppable_field_selector.js",
            "pdfgeneratorapi_connector/static/src/mapping_editor/mapping_editor.scss",
            "pdfgeneratorapi_connector/static/src/template_editor/editor_iframe_field.js",
            "pdfgeneratorapi_connector/static/src/template_editor/editor_iframe_field.xml",
            "pdfgeneratorapi_connector/static/src/template_editor/template_selection_field.js",
            "pdfgeneratorapi_connector/static/src/template_editor/template_selection_field.xml",
            "pdfgeneratorapi_connector/static/src/template_editor/template_editor.scss",
            "pdfgeneratorapi_connector/static/src/settings/settings.scss",
        ],
        "web.assets_unit_tests": [
            "pdfgeneratorapi_connector/static/tests/**/*.test.js",
        ],
    },
    "images": [
        "static/description/pdfgeneratorapi_odoo_cover_560x315.png",
        "static/description/template_settings_2.png",
        "static/description/send_invoice_1.png",
        "static/description/field_datasets_settings_2.png",
        "static/description/batch_generation_2.png",
        "static/description/settings_1.png",
    ],
    "application": True,
}
